version: '3'

services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - db



  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: